[datasets.key_measures.annual]
title = "Key Performance Measures (Annual)"
description = "Annual referrals, assessments, treatment completions, recovery rates, waiting times by organisation"
version = "0.2.0"
get_function = "get_key_measures_annual"

[[datasets.key_measures.annual.sources]]
period = "2017-18"
url = "https://files.digital.nhs.uk/82/2CCBED/psych-ther-ann-2017-18-csvs.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2017-18-main-csv.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2018-19"
url = "https://files.digital.nhs.uk/88/EBA9A6/psych-ther-ann-2018-19-csvs.rar"
format = "rar"
csv_file = "psych-ther-ann-rep-csv-2018-19-main-csv.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2019-20"
url = "https://files.digital.nhs.uk/1A/F2ABB3/psych-ther-ann-2019-20-csvs.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2019-20-main-csv.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2020-21"
url = "https://files.digital.nhs.uk/62/DBF395/psych-ther-ann-rep-csvs-2020-21.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2020-21-main-csv-v2.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2021-22"
url = "https://files.digital.nhs.uk/DC/9E8751/psych-ther-ann-rep-csvs-2021-22.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2021-22-main-csv.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2022-23"
url = "https://files.digital.nhs.uk/CA/8F53D1/psych-ther-ann-rep-csvs-2022-23.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2022-23-main-v2.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2023-24"
url = "https://files.digital.nhs.uk/4E/6D88C2/psych-ther-ann-rep-csvs-2023-24.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2023-24-main.csv"
csv_pattern = "main"

[[datasets.key_measures.annual.sources]]
period = "2024-25"
url = "https://files.digital.nhs.uk/4E/2104A0/psych-ther-ann-rep-csv-2024-25-2.zip"
format = "zip"
csv_file = "psych-ther-ann-rep-csv-2024-25-main2.csv"
csv_pattern = "main"

[datasets.activity_performance.monthly]
title = "Activity and Performance Measures (Monthly)"
description = "Monthly activity and performance indicators by organisation"
version = "0.2.0"
get_function = "get_activity_performance_monthly"
make_clean_names = ["measure"]

[[datasets.activity_performance.monthly.sources]]
period = "2023-05"
url = "https://files.digital.nhs.uk/5A/7859F6/nhstalkingtherapies_month_may_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-06"
url = "https://files.digital.nhs.uk/3F/D75B04/nhstalkingtherapies_month_jun_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-07"
url = "https://files.digital.nhs.uk/D6/7E8345/nhstalkingtherapies_month_jul_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-08"
url = "https://files.digital.nhs.uk/64/7F735D/nhstalkingtherapies_month_aug_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-09"
url = "https://files.digital.nhs.uk/CA/27F447/nhstalkingtherapies_month_sep_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-10"
url = "https://files.digital.nhs.uk/13/EAED48/nhstalkingtherapies_month_oct_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-11"
url = "https://files.digital.nhs.uk/F6/57F7F3/nhstalkingtherapies_month_nov_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2023-12"
url = "https://files.digital.nhs.uk/D7/8264F5/nhstalkingtherapies_month_dec_2023_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-01"
url = "https://files.digital.nhs.uk/62/7CCA0D/nhstalkingtherapies_month_jan_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-02"
url = "https://files.digital.nhs.uk/26/0B5CA5/nhstalkingtherapies_month_feb_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-03"
url = "https://files.digital.nhs.uk/4D/5A8BC7/nhstalkingtherapies_month_mar_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-04"
url = "https://files.digital.nhs.uk/30/50A7CE/nhstalkingtherapies_month_apr_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-05"
url = "https://files.digital.nhs.uk/29/B7E3E8/nhstalkingtherapies_month_may_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-06"
url = "https://files.digital.nhs.uk/3B/3DC051/nhstalkingtherapies_month_jun_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-07"
url = "https://files.digital.nhs.uk/3A/AEF808/nhstalkingtherapies_month_jul_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-08"
url = "https://files.digital.nhs.uk/CE/BB6A21/nhstalkingtherapies_month_aug_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-09"
url = "https://files.digital.nhs.uk/AF/0ECF15/nhstalkingtherapies_month_sep_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-10"
url = "https://files.digital.nhs.uk/27/016EFD/nhstalkingtherapies_month_oct_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-11"
url = "https://files.digital.nhs.uk/2D/AA889E/nhstalkingtherapies_month_nov_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2024-12"
url = "https://files.digital.nhs.uk/B8/E2E4AF/nhstalkingtherapies_month_dec_2024_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-01"
url = "https://files.digital.nhs.uk/5B/4A488A/nhstalkingtherapies_month_jan_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-02"
url = "https://files.digital.nhs.uk/B4/A9E30F/nhstalkingtherapies_month_feb_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-03"
url = "https://files.digital.nhs.uk/D8/C94D7C/nhstalkingtherapies_month_mar_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-04"
url = "https://files.digital.nhs.uk/B7/F15915/nhstalkingtherapies_month_apr_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-05"
url = "https://files.digital.nhs.uk/5C/5C7F78/nhstalkingtherapies_month_may_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-06"
url = "https://files.digital.nhs.uk/CE/3E3DA3/nhstalkingtherapies_month_jun_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-07"
url = "https://files.digital.nhs.uk/30/203A87/nhstalkingtherapies_month_jul_2025_activity_final.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-08"
url = "https://files.digital.nhs.uk/93/B77ED0/nhstalkingtherapies_month_aug_2025_activity_performance.csv"
format = "csv"

[[datasets.activity_performance.monthly.sources]]
period = "2025-09"
url = "https://files.digital.nhs.uk/0C/824E81/nhstalkingtherapies_month_sep_2025_activity_performance.csv"
format = "csv"
